steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/cloudrun-hello', '.']

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "eu.gcr.io/$PROJECT_ID/cloudrun-hello"]

  - name: 'eu.gcr.io/$PROJECT_ID/cloudrun-hello'
    args: ['pytest']

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "cloudrun-hello",
        "--image",
        "eu.gcr.io/$PROJECT_ID/cloudrun-hello",
        "--region",
        "europe-west1",
        "--allow-unauthenticated",
        "--platform",
        "managed",
      ]